import Header from "@/components/app/header";
import Sidebar from "@/components/app/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <Sidebar />
        <div className="flex h-screen overflow-hidden flex-col sm:pl-14 relative">
          <Header />
          <main className="flex-1 items-start gap-4 p-4 sm:px-6 sm:py-4 md:gap-8 overflow-auto">
            {children}
          </main>
        </div>
      </div>
    </TooltipProvider>
  );
}
